@VietnamTrafficPolice.WebApi_HostAddress = http://localhost:5237
#@VietnamTrafficPolice.WebApi_HostAddress = https://localhost:7162

GET {{VietnamTrafficPolice.WebApi_HostAddress}}/traffic-incident?plateId=1
Accept: application/json

